<form action='/delete' method='post'>
<ul>
<?php foreach ($unserializedHumans as $id => $human):?>
<ul>
  <li> Vorname: <?= $human->getFirstName() ?> </li> 
  <li> Nachname: <?= $human->getLastName() ?></li>
  <li> Alter: <?= $human->getAge() ?></li>
  <li> Beruf: <?= $human->getProfession()->toString() ?></li>

  <li> <label for='id'>Delete: <input type="submit" value=<?=$id?> name="id"> </li>


</ul>
<?php endforeach ?>
</ul>